titles: # https://docs.adventure.kyori.net/minimessage/format.html
  enter:
    enabled: true
    title: '<white>%player%''s Claim'
    subtitle: ''
    actionbar: ''
  exit:
    enabled: true
    title: ''
    subtitle: '<white>Wilderness'
    actionbar: ''

watched-worlds: # worlds that will be watched
  enable: false # if enable is false, all worlds will be watched
  worlds: # worlds that will be watched
    - world
    - world_nether
    - world_the_end

show-on-dimension-switch: true
show-on-admin-claim: true # Should we show a title for admin claims?