name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: plugin-version
    attributes:
      label: Plugin Version
      description: What version of GriefPreventionTitles are you running?
      placeholder: ex. 1.4.0
    validations:
      required: true

  - type: input
    id: server-version
    attributes:
      label: Server Version
      description: What server software and version are you running?
      placeholder: ex. Paper 1.20.1-196
    validations:
      required: true

  - type: input
    id: grief-prevention-version
    attributes:
      label: GriefPrevention Version
      description: What version of GriefPrevention are you using?
      placeholder: ex. 16.18.2
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Run command /toggleclaimtitles
        2. Enter a claim
        3. See error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Badbird5907/GriefPreventionTitles/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true